# -*- coding: utf-8 -*-
"""dataCleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10dG1qRS0QbpmZLiUSvWjaWYymA6xkl43

# **Limpieza de datos**
"""

import pandas as pd

df = pd.read_csv('output.csv')

"""**Eliminando columnas sin importancia**"""

df.drop(['conversation_id', 'created_at', "time",	"timezone", "user_id",	"username",	"name",	"place", "mentions",	"urls"	,"photos",	"replies_count",	"retweets_count",	"likes_count"	,"hashtags"	,"cashtags", "retweet", "quote_url",	"video",	"thumbnail","source" ,"near"	,"user_rt_id","user_rt","retweet_id"	,"reply_to"	,"retweet_date"	,"translate"	,"trans_src"	,"trans_dest"  ], axis=1, inplace=True)

"""**Eliminando datos repetidos**"""

df.drop_duplicates(subset ="id", keep = False, inplace = True)
df = df.set_index("id")

"""**Eliminando lenguajes diferentes al Español e inglés**"""

df = df[(df['language'] == "es") | (df['language'] == "en")]

df["date"].value_counts()